name: shelf_essentials
description: "Essential utilities and middleware for building web servers with Shelf in Dart and Flutter."
version: 1.0.1
repository: https://github.com/k-arindam/shelf_essentials
documentation: https://karindam.in/shelf_essentials

funding:
  - https://github.com/sponsors/k-arindam

topics:
  - dart
  - flutter
  - shelf
  - backend
  - web-server

environment:
  sdk: ^3.10.1

dependencies:
  shelf: ^1.4.2
  http_parser: ^4.1.2
  mime: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec